module.exports = {
  en: {
    siteTitle: 'iPhone, Mac, Android, Web, Cloud, VR, AR Professional Development',
    mainTitle: 'Pro Software Development with love ;)',
    crewTitle: 'The<br /><h3>crew</h3>',
    rollingTheRocks: 'Rolling the rocks!',
    visionAndCode: 'Vison & code',
    webCoder: 'webeloper',
    coder: 'coder',
    aboutUs: 'Here we are! We are a small but very motivated developer team. We are geeks. We are professionals working in the IT-industry more than 15 years. We create cool, modern software!',
    slogen: 'We bring your brilliant app ideas into reality!',
    worksTitle: 'recent<br /><h3>works</h3>',

    teammeloName: 'TeamMelo',
    teammeloTags: '<a href="https://en.wikipedia.org/wiki/Swift_(programming_language)">swift</a> <a href="https://en.wikipedia.org/wiki/Firebase">firebase</a> <a href="https://en.wikipedia.org/wiki/Cross-platform">multiplatform</a>  <a href="https://vuejs.org">vue.js</a>',
    teammeloDesc: 'TeamMelo is a techdemo using modern technologies like Firebase. It\'s real-time and highly scalable and lightweight. Maybe it will not in the top downloads, but gonna check the <a href="http://teammelo.io">the real-time website</a> of the app! Can you imagine how this real-time, multiplatform technology could help your idea\'s becoming reality?',

    crayhuName: 'Cray.hu',
    crayhuTags: '<a href="https://threejs.org">THREE.js</a> <a href="https://en.wikipedia.org/wiki/8-bit">8bit</a> <a href="http://akira.wikia.com/wiki/Neo-Tokyo">neo-tokyo</a>',
    crayhuDesc: 'Design & HTML and a little more. Using the cool three.js javascript 3D engine to bring back the late 80\'s when Neo-Tokyo was our dream. Spheres are dancing to the audio, the camera spins around and how cool is the track? Bring back from our 8bit childhood feeling and having it last for a while ;)',

    cubiccalcName: 'CubicCalc',
    cubiccalcTags: '<a href="https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/index.html">swift</a> <a href="https://en.wikipedia.org/wiki/Kotlin_(programming_language)">kotlin</a> <a href="https://en.wikipedia.org/wiki/IOS">ios</a> <a href="https://en.wikipedia.org/wiki/Android_(operating_system)">android</a> <a href="https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CoreData/index.html">coredata</a>',
    cubiccalcDesc: 'CubicCalc is a professional log volume measuring tool specifically created for foresters. It\'s a simple but demanding app using Core Data under the hood. Developed in Swift and Kotlin too, so native on iOS and Android too.',

    earthquakesName: 'Earthquakes',
    earthquakesTags: '<a href="https://en.wikipedia.org/wiki/Swift_(programming_language)">swift</a> <a href="https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html">APNs</a> <a href="https://www.java.com/en/">java</a>',
    earthquakesDesc: 'It\'s a very simple app. A lightweight client connected to a tiny backend supporting APNs.',

    whatWeLove: 'We love a bunch of technologies',
    readyToLearn: 'and we are always ready to learn something new, and these are some of our nowaday favourites.',
    swiftDesc: 'It\'s sexy, it\'s cool, it\'s Apple!<br />The full power of iOS and macOS is under your controll!',
    nodeDesc: '<a href=\"https://nodejs.org\">Javascript on the server side!</a> One language from client to server. How cool that is!',
    firebaseDesc: '<a href="https://firebase.google.com">Firebase</a> is a <a href="https://en.wikipedia.org/wiki/Real-time_database">real-time</a> and multiplatform, auto-scaling, cheap and cloud-hosted database by Google. Need more?',
    kotlinDesc: '<a href="https://kotlinlang.org">Kotlin</a> is the successor of Java, now <a href="https://developer.android.com/kotlin/index.html">official on Android</a>! Thank you <a href="https://www.jetbrains.com">JetBrains</a>, thank you Google!',
    vueDesc: '<a href="https://vuejs.org">Vue.js</a> is a modern <a href="https://en.wikipedia.org/wiki/Front-end_web_development">front-end javascript framework</a>. Perfect solution for your next feature-filled  modern <a href="https://en.wikipedia.org/wiki/Web_application">webapps</a>!',
    cssHtmlDesc: '<a href="https://en.wikipedia.org/wiki/Cascading_Style_Sheets">CSS</a> & <a href="https://en.wikipedia.org/wiki/HTML">HTML</a> are the \'languages\' of the web, so we love them... and sometimes hate them too ;)',
    mission: 'Mission',
    missionTitle: 'Pro Software Development',
    goals: 'Goals',
    goalFirst: 'Acquiring satisfied customers!',
    goalSecond: 'Create cool software!',
    goalThird: 'Learning new things!',
    more: 'more',
    less: 'less',
    address: 'Address',
    addressFirst: 'Hungary,',
    addressSecond: '2028 Pilismarot,',
    addressThird: 'Kossuth Lajos u. 2/b',
    taxId: 'tax ID:',
    regId: 'reg ID:',
    english: 'en',
    hungarian: 'hu'
  },
  hu: {
    siteTitle: "iPhone, Mac, Android, Web, Cloud, VR, AR Profi Szoftverfejlesztés",
    mainTitle: 'Profi Szoftverfejlesztés, szeretettel ;)',
    crewTitle: 'A<br /><h3>csapat</h3>',
    rollingTheRocks: 'Vezeti a csapatot!',
    visionAndCode: 'Újakat talál ki',
    webCoder: 'webprogramozó',
    coder: 'programozó',
    welcome: 'Szép napot, {name}',
    aboutUs: 'Itt vagyunk! Kicsi, de nagyon elszánt csapat, kockák, profik, akik az IT-iparban dolgoznak, több, mint 15 éve és modern, menő szoftvereket készítenek!',
    slogen: 'Megvalósítjuk a szenzációs App-ötletedet!',
    worksTitle: 'utóbbi<br /><h3>melók</h3>',

    teammeloName: 'TeamMelo',
    teammeloTags: '<a href="https://hu.wikipedia.org/wiki/Swift_(programozási_nyelv)">swift</a> <a href="https://en.wikipedia.org/wiki/Firebase">firebase</a> <a href="https://hu.wikipedia.org/wiki/Platformfüggetlenség">multiplatform</a>  <a href="https://vuejs.org">vue.js</a>',
    teammeloDesc: 'A TeamMelo egy technikai demó alkalmazás, ami a Firebase valósidejű adatbázisra épül. Többfelhasználós, valós idejű, modern feladat-megosztó alkalmazás, Facebook és Google Sign In integrációval. Egy chat és egy to-do alkalmazás ötvözete. Nézd meg a <a href="http://teammelo.io">valós idejű websiteot</a> és képzeld el, hogy ezek a technológiát milyen nagy segítséget nyújthatnak a Te szoftveredben.',

    crayhuName: 'Cray.hu',
    crayhuTags: '<a href="https://threejs.org">THREE.js</a> <a href="https://hu.wikipedia.org/wiki/8_bites_architektúra">8bit</a> <a href="http://akira.wikia.com/wiki/Neo-Tokyo">neo-tokyo</a>',
    crayhuDesc: 'Design és HTML, meg egy kis plusz. A menő three.js javascript 3D library-t használva, megpróbáltuk visszahozni a késő 80-as évek hangulalát, életre kelteni Neo-Tokiót. A gömbök ütemre mozognak a kamera körbe-körbe megy. A8 bites gyerekkorunk visszatér egy pillanatra ;)',

    cubiccalcName: 'Köböző',
    cubiccalcTags: '<a href="https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/index.html">swift</a> <a href="https://hu.wikipedia.org/wiki/Kotlin_(programozási_nyelv)">kotlin</a> <a href="https://hu.wikipedia.org/wiki/IOS">ios</a> <a href="https://hu.wikipedia.org/wiki/Android_(operációs_rendszer)">android</a> <a href="https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CoreData/index.html">coredata</a>',
    cubiccalcDesc: 'A Köböző egy professzionális rönktérfogat-számító alkalmazás, elsősorban erdészek számára. Ez egy egyszerű, de igényes alalmazás, ami Swiftben és Kotlinban egyaránt le lett fejlesztve, így iPhone-on és Android-on is natív alkalmazásként fut.',

    earthquakesName: 'Földrengések',
    earthquakesTags: '<a href="https://hu.wikipedia.org/wiki/Swift_(programozási_nyelv)">swift</a> <a href="https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html">APNs</a> <a href="https://www.java.com/en/">java</a>',
    earthquakesDesc: 'Egy nagyon egyszerű alkalmazás, ami egy kis szerverhez csatlakozik. A valós idejű üzenetek küldéséhez az APNs technológiát használja.',

    whatWeLove: 'Sokféle technológát szeretünk',
    readyToLearn: 'és szeretünk új dolgokat tanulni. Itt van néhány a legújabb kedvenceink közül:',
    swiftDesc: 'Szexi, menő, egyszóval Apple<br />Vele az iOS és macOS teljes ereje a Te irányításod alatt!',
    nodeDesc: '<a href="https://csomónodejs.org">Javascript a szerveroldalon!</a> Egy nyelv a klienstől a szerverig! Ez menő!',
    firebaseDesc: 'A <a href="https://firebase.google.com">Firebase</a> egy <a href="https://en.wikipedia.org/wiki/Real-time_database">valós idejű</a>, multiplatform, ún. auto-scaling, olcsó és felhő-alapú adatbázis a Googletől. Kell ennél több?',
    kotlinDesc: 'A <a href="https://kotlinlang.org">Kotlin</a> a Java nyelv utódja, ami már <a href="https://developer.android.com/kotlin/index.html">hivatalos nyelve az Androidon</a>! Köszi <a href="https://www.jetbrains.com">JetBrains</a>, köszi Google!',
    vueDesc: 'A <a href="https://vuejs.org">Vue.js</a> egy modern <a href="https://en.wikipedia.org/wiki/Front-end_web_development">javascript kliens-oldali keretrendszer</a>. Kiváló megoldás a modern, menő <a href="https://en.wikipedia.org/wiki/Web_application">webapp</a>odhoz!',
    cssHtmlDesc: 'A <a href="https://hu.wikipedia.org/wiki/Cascading_Style_Sheets">CSS</a> és <a href="https://hu.wikipedia.org/wiki/HTML">HTML</a> a Web \'nyelvei\', ezért szeretjük... és néha gyűlöljük is őket ;)',
    mission: 'Küldetés',
    missionTitle: 'Profi Szoftverfejlesztés',
    goals: 'Célok',
    goalFirst: 'Elégedett ügyfeleket gyűjteni!',
    goalSecond: 'Menő appokat készíteni!',
    goalThird: 'Új dolgokat tanulni!',
    more: 'több',
    less: 'csuk',
    address: 'Cím:',
    addressFirst: '',
    addressSecond: '2028 Pilismarót,',
    addressThird: 'Kossuth Lajos u. 2/b',
    taxId: 'Adósz.:',
    regId: 'Cg.:',
    english: 'en',
    hungarian: 'hu'
  },
}
